# Generated by Django 2.1.7 on 2019-03-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_auto_20190314_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='positng',
            new_name='posting',
        ),
    ]
