# Generated by Django 2.1.7 on 2019-03-13 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Article')),
            ],
        ),
    ]
